name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
#   release:
#     types: [released]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    # if: ${{ github.repository_owner == 'MaaXYZ' }}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [android]
    #     arch: [arm64, x86_64]
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "*universal.apk"
          mirrorchyan_rid: MAA-Meow
          tag: ${{ inputs.tag }}

          os: android
          # arch:

          owner: Aliothmoon
          repo: MAA-Meow
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}